---
environment: "debug"
db:
  driver: "mysql"
  connection: "user:mypass@(127.0.0.1:3306)/mydb"
log:
  level: "debug"
  output: "data/logs"
  max_file_size: 100
  max_days: 30
  max_file_num: 5
http:
  host: "0.0.0.0"
  port: "8080"
data_dir:
  inference_tasks: "data/inference_tasks"
blockchain:
  rpc_endpoint: "https://block-node.crynux.ai/rpc"
  start_block_num: 162233
  gas_limit: 4294967
  account:
    address: ""
  contracts:
    task: "0x66C6976550B83D813f8165DF781e8578A988D467"
    node: "0x83BA661ED688238870Bd89d4F5Bb517F0e19196A"
    crynux_token: "0xB627D84BFB8cC311A318fEf679ee498F822A0C7C"
test:
  root_account: ""